### ISSUE TITLE
[Feat] Object Mapper / Exception 방식 결정

### ISSUE THREAD

**Issue by kimminkyeu** [Kernel360/E2E2-LOOK-US#15]
### TODO
- [x] Object Mapper 방식 결정
  - `option 1` : `@JsonProperty`로 모든 엔티티에 이름을 명시한다.
  - `option 2` : `@JsonNaming`으로 전체 프로퍼티를 매핑한다.
  - `option 3` : application.yaml 파일에 `MyBatis` 규칙을 적는다.
     - 다만 걱정은 너무 많은 패키지가 포함될까봐...
     - 근데 개발할 때 편함
     ```yaml
      # build.gradle
      implementation 'org.mybatis.spring.boot:mybatis-spring-boot-starter:3.0.0'
      # application.yaml
      mybatis:
        configuration:
          map-underscore-to-camel-case: true 추가 
     ```

### option 2 : JsonNaming 방식으로 선정하였습니다.
